### ISSUE TITLE
Dashboard not updating

### ISSUE THREAD

**Issue by WGS-SysAdmin** [Chateau-Lav/pihole#3]
I'm new to Graylog so be patient as I learn.   I installed Graylog last week and have successfully ingested log data from Windows, Linux and my Firewall.  I downloaded and installed this Content Pack and without issue began ingesting data... but nothing on the Dashboard.  I'm running Graylog 4.0.7 and PiHole 5.3.1  Is there something I'm missing in the Extractor or Dashboard that I should have edited?  Or should it have worked "out of the box?"

**Comment by Chateau-Lav** [comment]
Do you have any further details in regards to the data being ingested? while you don't see the dashboard populating, is the data at least available and searchable?

It should work pretty much out of the box as long as you are ingesting properly. The pihole logs should be coming over port 1515.

I cannot attest to the functionality beyond the graylog version at the the time when this plugin was released, as i do not currently operate graylog in my environment anymore. I am more then willing to assist and keep this up to date though, feel free to send me an email and we can setup a voice or screen share session to troubleshoot your issues.

**Comment by WGS-SysAdmin** [comment]
The data seems fine and the extractor is pulling messages.  The details from the Extractor show:
Metrics
222,205 total invocations since boot, averages: 4.58, 4.45, 3.82.
217614 hits, 4591 misses

looks to me like it's shoving them someplace called "application_name" (I assume a field in Elastisearch) but is never getting pulled from the Dashboard.  I checked the Graylog_server logs and there aren't any relevant entries.  I don't know how to check the dashboard to see where it's getting data.  I can only believe it's looking somewhere that has changed over the versions.

db

**Comment by Chateau-Lav** [comment]
part of the dashboard setup is targeted toward a specific source named `pihole`, I recommend opening the dashboard and then editing it. the base query that it being used to pull the data into the dashboard should target the source for you pihole data. If you could add a screenshot or sample output of one of the pihole logs with its associated elastic fields that would be great. 

it seems like the base query just needs updated to pull in the correct logs

**Comment by WGS-SysAdmin** [comment]
Well, so there's the rub.  I can open the dashboard but I find no way of editing anything but the Metadata or the individual widgets.  I can't find any indication of a "source" of data to edit.

**Comment by Chateau-Lav** [comment]
So it is built in a way that the widgets are built off each other, so to edit the query you have to do it at the widget level. I believe the top left widget is the anchor with the main query. shot me message on discord if you want to quickly resolve this and ill document and further requirements in regards to updating the github content.

Chateau-Lav#5536

**Comment by chateaulav** [comment]
refinement of docs and grok patterns to better account for personal implementation in any environment. accounting for better log parsing and requirements needed for personal implementation.

**Comment by WGS-SysAdmin** [comment]
Your prompt response and help is greatly appreciated!
